#!/bin/bash
: ${APP_HOME_DIR:=/app}
: ${APP_CURRENT_DIR:=/app/current}
: ${APP_UID:=3000}
: ${APP_GID:=3000}
: ${APP_SERVER_CMD:=exec bin/rails server -b0}

find "${APP_HOME_DIR}" -xdev \( -not -uid ${APP_UID} -o -not -gid ${APP_GID} \) -print0 | xargs -r0 chown -h "${APP_UID}:${APP_GID}"

if [ "$(id -g rails)" -ne "${APP_GID}" ]; then
  groupmod --non-unique --gid "${APP_GID}" rails
fi
if [ "$(id -u rails)" -ne "${APP_UID}" ]; then
  usermod --non-unique --uid "${APP_UID}" rails
fi

for pidfile in "${APP_CURRENT_DIR}"/tmp/pids/*.pid; do
  if [ -f "${pidfile}" -a ! -e "/proc/$(< ${pidfile})" ]; then
    echo "Remove orphaned pidfile: ${pidfile}"
    rm "${pidfile}"
  fi
done

cd "${APP_CURRENT_DIR}"
exec su -p -s /bin/bash -c "${APP_SERVER_CMD}" rails
