#!/bin/bash
: ${APP_HOME_DIR:=/app}
: ${APP_CURRENT_DIR:=/app/current}
: ${APP_UID:=3000}
: ${APP_GID:=3000}
: ${APP_SERVER_CMD:=exec bin/rails server -b0}

find "${APP_HOME_DIR}" -xdev -print0 | xargs -r0 chown -h "${RAILS_UID}:${RAILS_GID}"

if [ "$(id -g rails)" -ne "${APP_GID}" ]; then
  groupmod --non-unique --gid "${APP_GID}" rails
fi
if [ "$(id -u rails)" -ne "${APP_UID}" ]; then
  usermod --non-unique --uid "${APP_UID}" rails
fi

cd "${APP_CURRENT_DIR}"
exec su -p -s /bin/bash -c "${APP_SERVER_CMD}" rails
